name: notulensi
description: "Notulensi: 100% Offline Private Meeting Assistant"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management & Routing
  get: ^4.6.6
  equatable: ^2.0.5
  
  # Persistence
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  
  # Security
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.8
  encrypt: ^5.0.3
  permission_handler: ^11.3.1
  
  # UI & Design System
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  
  # Intelligence
  speech_to_text: ^7.3.0
  record: ^5.1.0
  audioplayers: ^5.2.1
  share_plus: ^12.0.2
  google_mobile_ads: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mocktail: ^1.0.3
  
  # Code Generation
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
