name: notulensi
description: "Notulensi: 100% Offline Private Meeting Assistant"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management & Routing
  get: ^4.6.6
  equatable: ^2.0.5
  
  # Persistence
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  
  # Security
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.8
  encrypt: ^5.0.3
  permission_handler: ^11.3.1
  
  # UI & Design System
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  intl: 0.20.2
  
  # Intelligence
  speech_to_text: ^7.3.0
  record: ^5.1.0
  audioplayers: ^5.2.1
  share_plus: ^12.0.2
  google_mobile_ads: ^8.0.0
  ffmpeg_kit_flutter_full_gpl: ^6.0.3
  path_provider_platform_interface: ^2.1.2
  storage_space: ^1.2.0
  perfect_volume_control: ^1.0.6
  flutter_localizations:
    sdk: flutter
  pdf: ^3.12.0
  printing: ^5.14.3
  fl_chart: ^1.2.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.2.0
  archive: ^4.0.9
  camera: ^0.12.0+1
  path: ^1.9.1
  image_picker: ^1.2.1
  add_2_calendar: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mocktail: ^1.0.3
  
  # Code Generation
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  generate: true
