// Mocks generated by Mockito 5.4.4 from annotations
// in notulensi/test/features/recording/logic/recording_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:notulensi/core/permissions/permission_service.dart' as _i5;
import 'package:notulensi/features/notes/services/note_management_service.dart'
    as _i2;
import 'package:notulensi/shared/models/database/meeting_note.dart' as _i4;
import 'package:permission_handler/permission_handler.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NoteManagementService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNoteManagementService extends _i1.Mock
    implements _i2.NoteManagementService {
  @override
  _i3.Future<void> updateNote(_i4.MeetingNote? note) => (super.noSuchMethod(
        Invocation.method(
          #updateNote,
          [note],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteNote(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteNote,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> createNoteWithAudio({
    required String? title,
    required String? transcript,
    required int? duration,
    String? audioPath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNoteWithAudio,
          [],
          {
            #title: title,
            #transcript: transcript,
            #duration: duration,
            #audioPath: audioPath,
          },
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> createNote(
    String? title,
    String? transcript, {
    int? duration = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNote,
          [
            title,
            transcript,
          ],
          {#duration: duration},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [PermissionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionService extends _i1.Mock implements _i5.PermissionService {
  @override
  _i3.Future<_i6.PermissionStatus> status(_i6.Permission? permission) =>
      (super.noSuchMethod(
        Invocation.method(
          #status,
          [permission],
        ),
        returnValue:
            _i3.Future<_i6.PermissionStatus>.value(_i6.PermissionStatus.denied),
        returnValueForMissingStub:
            _i3.Future<_i6.PermissionStatus>.value(_i6.PermissionStatus.denied),
      ) as _i3.Future<_i6.PermissionStatus>);

  @override
  _i3.Future<_i6.PermissionStatus> request(_i6.Permission? permission) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [permission],
        ),
        returnValue:
            _i3.Future<_i6.PermissionStatus>.value(_i6.PermissionStatus.denied),
        returnValueForMissingStub:
            _i3.Future<_i6.PermissionStatus>.value(_i6.PermissionStatus.denied),
      ) as _i3.Future<_i6.PermissionStatus>);

  @override
  _i3.Future<bool> isGranted(_i6.Permission? permission) => (super.noSuchMethod(
        Invocation.method(
          #isGranted,
          [permission],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> openAppSettings() => (super.noSuchMethod(
        Invocation.method(
          #openAppSettings,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> requestMicrophone() => (super.noSuchMethod(
        Invocation.method(
          #requestMicrophone,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> requestCamera() => (super.noSuchMethod(
        Invocation.method(
          #requestCamera,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
