import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:intl/intl.dart';
import '../../../shared/models/database/meeting_note.dart';

class TextExportService {
  Future<void> exportNoteAsTxt(MeetingNote note) async {
    final date = DateFormat('yyyy-MM-dd').format(note.createdAt);
    final fileName = '${note.title.replaceAll(RegExp(r'[^\w\s-]'), '')}_$date.txt';
    
    final content = '''
TITLE: ${note.title}
DATE: ${DateFormat('EEEE, MMM dd, yyyy').format(note.createdAt)}
DURATION: ${_formatDuration(Duration(seconds: note.durationSeconds))}

TRANSCRIPT:
${note.transcript}

Generated by Notulensi
''';

    final directory = await getTemporaryDirectory();
    final file = File('${directory.path}/$fileName');
    await file.writeAsString(content);

    // ignore: deprecated_member_use
    await Share.shareXFiles([XFile(file.path)], text: 'Meeting Note: ${note.title}');
  }

  String _formatDuration(Duration d) {
    final h = d.inHours;
    final m = d.inMinutes.remainder(60);
    final s = d.inSeconds.remainder(60);
    if (h > 0) return '${h}h ${m}m ${s}s';
    return '${m}m ${s}s';
  }
}
